variant: flatcar
version: 1.0.0
storage:
  files:
    - path: /etc/systemd/system/sftp-mc.service
      mode: 0644
      contents:
        inline: |
          [Unit]
          Description=SFTP Server for PaperMC Data
          After=docker.service
          Requires=docker.service

          [Service]
          Restart=on-failure
          RestartSec=30
          StandardOutput=journal
          StandardError=journal
          ExecStart=/usr/bin/docker run --name sftp -p 2223:22 -v papermc-data:/home/minecraftuser/papermc ghcr.io/atmoz/sftp/debian minecraftuser:password:::papermc
          ExecStop=/usr/bin/docker stop sftp
          ExecStopPost=/usr/bin/docker rm sftp

          [Install]
          WantedBy=multi-user.target

    - path: /etc/systemd/system/minecraft.service
      mode: 0644
      contents:
        inline: |
          [Unit]
          Description=PaperMC Minecraft Server
          After=docker.service
          Requires=docker.service

          [Service]
          Restart=always
          RestartSec=20
          StandardOutput=journal
          StandardError=journal
          Environment="EULA=true"
          Environment="MC_VERSION=latest"
          Environment="PAPER_BUILD=latest"
          Environment="MC_RAM=4G"
          Environment="JAVA_OPTS=-Xms4G -Xmx4G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M"
          Environment="ENABLE_RCON=true"
          Environment="RCON_PASSWORD=your_rcon_password"
          Environment="RCON_PORT=25575"
          ExecStart=/usr/bin/docker run --name papermc -p 25565:25565 -p 25575:25575 --memory="4g" --memory-swap="4g"  -e EULA=true -e MC_VERSION=latest -e PAPER_BUILD=latest -e MC_RAM=4G -e JAVA_OPTS="-Xms4G -Xmx4G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M" -e ENABLE_RCON=true -e RCON_PASSWORD=your_rcon_password -e RCON_PORT=25575 -v papermc-data:/papermc phyremaster/papermc
          ExecStop=/usr/bin/docker stop papermc
          ExecStopPost=/usr/bin/docker rm papermc

          [Install]
          WantedBy=multi-user.target

systemd:
  units:
    - name: docker.service
      enabled: true
    - name: sftp-mc.service
      enabled: true
    - name: minecraft.service
      enabled: true
