variant: flatcar
version: 1.0.0
storage:
  files:
    - path: /etc/systemd/system/sshd-sftp.service
      mode: 0644
      contents:
        inline: |
          [Unit]
          Description=Separate SFTP Server on Port 2223
          After=network-online.target sshd.service
          Wants=network-online.target

          [Service]
          ExecStart=/usr/sbin/sshd -D -f /etc/ssh/sshd_config -p 2223
          Restart=always
          RestartSec=10

          [Install]
          WantedBy=multi-user.target

    - path: /etc/systemd/system/minecraft.service
      mode: 0644
      contents:
        inline: |
          [Unit]
          Description=PaperMC Minecraft Server
          After=docker.service
          Requires=docker.service

          [Service]
          User=core
          Group=core
          Restart=always
          RestartSec=20
          StandardOutput=journal
          StandardError=journal
          Environment="EULA=true"
          Environment="MC_VERSION=latest"
          Environment="PAPER_BUILD=latest"
          Environment="MC_RAM=4G"
          Environment="JAVA_OPTS=-Xms4G -Xmx4G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M"
          Environment="ENABLE_RCON=true"
          Environment="RCON_PASSWORD=your_rcon_password"
          Environment="RCON_PORT=25575"
          # Ensure the directory exists & set correct permissions
          ExecStartPre=/bin/mkdir -p /home/core/minecraft
          ExecStartPre=/bin/chown -R core:core /home/core/minecraft
          ExecStartPre=/bin/chmod -R 755 /home/core/minecraft
          ExecStart=/usr/bin/docker run --user 500:500 --name papermc \
            -p 25565:25565 -p 25575:25575 \
            --memory="4g" --memory-swap="4g" \
            -e EULA=true \
            -e MC_RAM=4G \
            -e ENABLE_RCON=true \
            -e RCON_PASSWORD=your_rcon_password \
            -e RCON_PORT=25575 \
            -v /home/core/minecraft:/papermc \
            ghcr.io/thijmengthn/papermc
          ExecStop=/usr/bin/docker stop papermc
          ExecStopPost=/usr/bin/docker rm papermc

          [Install]
          WantedBy=multi-user.target

systemd:
  units:
    - name: docker.service
      enabled: true
    - name: minecraft.service
      enabled: true
    - name: sshd-sftp.service
      enabled: true
