variant: flatcar
version: 1.0.0
storage:
  files:
    ########################################################################
    # Environment file (papermc.env)
    #
    # This file contains the "universal" environment variables for the
    # Minecraft Docker container, such as EULA acceptance and RCON info.
    ########################################################################
    - path: /etc/systemd/system/papermc.env
      mode: 0644
      contents:
        inline: |
          # We must accept the EULA for Minecraft.
          EULA=true

          # Use the "latest" available Paper build.
          MC_VERSION=latest
          PAPER_BUILD=latest

          # RCON (Remote Console) is enabled for external administration.
          ENABLE_RCON=true
          RCON_PASSWORD=your_rcon_password
          RCON_PORT=25575

          # This is the total Docker container memory. By default, set
          # to 4G. You can adjust this if you plan to switch environment
          # e.g., 2G, 8G, etc.
          DOCKER_RAM=4G

          # This is the memory setting for the Java process that will run the Minecraft server
          # It would be a bit lower than the total Docker container memory
          # to allow for the operating system and other processes to run
          MC_RAM=3G

          # Java specific options for tuning the JVM
          JAVA_OPTS="-XX:+UseG1GC \
           -XX:+ParallelRefProcEnabled \
           -XX:+UnlockExperimentalVMOptions \
           -XX:+DisableExplicitGC \
           -XX:+AlwaysPreTouch \
           -XX:G1HeapRegionSize=8M \
           -XX:G1NewSizePercent=20 \
           -XX:G1MaxNewSizePercent=40 \
           -XX:G1ReservePercent=20 \
           -XX:G1HeapWastePercent=5 \
           -XX:G1MixedGCCountTarget=4 \
           -XX:InitiatingHeapOccupancyPercent=15 \
           -XX:G1MixedGCLiveThresholdPercent=90 \
           -XX:G1RSetUpdatingPauseTimePercent=5 \
           -XX:SurvivorRatio=32 \
           -XX:MaxTenuringThreshold=1 \
           -XX:MaxGCPauseMillis=150 \
           -XX:+PerfDisableSharedMem \
           -Dusing.aikars.flags=https://mcflags.emc.gs \
           -Daikars.new.flags=true"



    ########################################################################
    # A separate SSHD-based SFTP service. Allows the administrator to access
    # Minecraft related files via a tool like Filezilla or WinSCP
    ########################################################################
    - path: /etc/systemd/system/sshd-sftp.service
      mode: 0644
      contents:
        inline: |
          [Unit]
          Description=Separate SFTP Server on Port 2223
          After=network-online.target sshd.service
          Wants=network-online.target

          [Service]
          ExecStart=/usr/sbin/sshd -D -f /etc/ssh/sshd_config -p 2223
          Restart=always
          RestartSec=10

          [Install]
          WantedBy=multi-user.target


    ########################################################################
    # The main Minecraft systemd unit.
    #
    # Key points:
    #   - We always load the "base" environment (papermc.env).
    #   - Uncomment ONE tier environment file for the Java GC flags you want.
    #   - The "MC_RAM" environment variable in papermc.env should match the
    #     Docker --memory limit you set. For instance, if you use small.env,
    #     set docker run --memory="4G".
    ########################################################################
    - path: /etc/systemd/system/minecraft.service
      mode: 0644
      contents:
        inline: |
          [Unit]
          Description=PaperMC Minecraft Server
          After=docker.service
          Requires=docker.service

          [Service]
          # Always load the base environment variables (EULA, RCON, etc.)
          EnvironmentFile=/etc/systemd/system/papermc.env

          # Docker run command: we pass environment variables (EULA, JAVA_OPTS, etc.)
          ExecStart=/usr/bin/docker run \
            --name papermc \
            -p 25565:25565 \
            -p 25575:25575 \
            --memory="${DOCKER_RAM}" \
            --memory-swap="${DOCKER_RAM}" \
            -e EULA=${EULA} \
            -e MC_VERSION=${MC_VERSION} \
            -e PAPER_BUILD=${PAPER_BUILD} \
            -e MC_RAM=${MC_RAM} \
            -e JAVA_OPTS="${JAVA_OPTS}" \
            -e ENABLE_RCON=${ENABLE_RCON} \
            -e RCON_PASSWORD=${RCON_PASSWORD} \
            -e RCON_PORT=${RCON_PORT} \
            -v papermc-data:/papermc \
            ghcr.io/thijmengthn/papermc

          ExecStop=/usr/bin/docker stop papermc
          ExecStopPost=/usr/bin/docker rm papermc

          [Install]
          WantedBy=multi-user.target

systemd:
  units:
    # Enable Docker
    - name: docker.service
      enabled: true

    # Enable the main Minecraft service
    - name: minecraft.service
      enabled: true

    # Enable the SSHD SFTP service
    - name: sshd-sftp.service
      enabled: true
